//! Parse and annotate LaTeX source. No compiled PDF participates in comparison.

mod bibliography;
mod expand;
mod lexer;
mod model;
mod render;

use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::{
    path::{Path, PathBuf},
    time::{Duration, Instant},
};

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SourceLocation {
    pub file: PathBuf,
    pub line: usize,
    pub column: usize,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Kind {
    Sentence,
    Figure,
    Table,
    Math,
    Heading,
    Bibliography,
    Block,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ChangeType {
    Removed,
    Added,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Change {
    pub change: ChangeType,
    #[serde(rename = "type")]
    pub kind: Kind,
    pub text: String,
    pub locations: Vec<SourceLocation>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Report {
    pub schema_version: u32,
    pub old: String,
    pub new: String,
    pub changed: bool,
    pub removed_sentences: usize,
    pub added_sentences: usize,
    pub removed_objects: usize,
    pub added_objects: usize,
    pub changes: Vec<Change>,
    pub warnings: Vec<String>,
}

pub struct Input<'a> {
    pub root: &'a Path,
    pub main: &'a Path,
}

pub struct Review {
    pub source: PathBuf,
    pub unified_source: PathBuf,
    pub old_source: Option<PathBuf>,
    pub new_source: Option<PathBuf>,
    pub assets: PathBuf,
    pub report: Report,
}

/// Detect an executable document environment, including entry points with an
/// included preamble. Comments and macro definitions do not become candidates.
pub fn is_main(source: &str, path: &Path) -> Result<bool> {
    if source.starts_with("% Generated by tex-diff.") {
        return Ok(false);
    }
    let tokens = lexer::tokens(source, path)?;
    let mut i = 0;
    while i < tokens.len() {
        if let Some(end) = expand::declaration_end(&tokens, i) {
            i = end;
            continue;
        }
        if tokens[i].command("begin")
            && lexer::group(&tokens, i + 1)
                .is_some_and(|(name, _)| lexer::source(name).trim() == "document")
        {
            return Ok(true);
        }
        i += 1;
    }
    Ok(false)
}

/// Compare LaTeX syntax and dependencies, then write one complete annotated
/// document. Compilation is a separate final step and supplies no diff input.
pub fn compare(
    old: Option<Input<'_>>,
    new: Option<Input<'_>>,
    directory: &Path,
    old_label: &str,
    new_label: &str,
    timeout: Duration,
) -> Result<Review> {
    let deadline = Instant::now() + timeout;
    let load = |input: Input<'_>, side| {
        let mut expanded = expand::load(input.root, input.main, deadline)?;
        bibliography::expand(&mut expanded, &directory.join(side), deadline)?;
        model::document(&expanded)
    };
    let old = old
        .map(|input| load(input, ".bibliography-old"))
        .transpose()?;
    let new = new
        .map(|input| load(input, ".bibliography-new"))
        .transpose()?;
    render::generate(
        old.as_ref(),
        new.as_ref(),
        directory,
        old_label,
        new_label,
        deadline,
    )
}
