//! Validate output paths and stage files before replacing saved reviews.

use anyhow::{Context, Result, ensure};
use std::{
    fs,
    path::{Path, PathBuf},
};

pub(crate) struct PdfDestination {
    path: PathBuf,
    temporary: Option<tempfile::TempDir>,
}

impl PdfDestination {
    pub(crate) fn new(requested: Option<&Path>, save: bool, create_pdf: bool) -> Result<Self> {
        let temporary = if requested.is_none() && !save && create_pdf {
            Some(
                tempfile::Builder::new()
                    .prefix("tex-diff-review-")
                    .tempdir()?,
            )
        } else {
            None
        };
        let path = requested.map(Path::to_owned).unwrap_or_else(|| {
            temporary.as_ref().map_or_else(
                || PathBuf::from("tex-diff.pdf"),
                |directory| directory.path().join("tex-diff.pdf"),
            )
        });
        if create_pdf || requested.is_some() {
            validate(&path, "pdf", "--output")?;
        }

        Ok(Self { path, temporary })
    }

    pub(crate) fn path(&self) -> &Path {
        &self.path
    }

    pub(crate) fn retain(&mut self) {
        // A desktop viewer can keep reading after tex-diff exits. Retain only
        // the completed PDF; the independent build workspace still cleans up.
        if let Some(directory) = self.temporary.take() {
            let _ = directory.keep();
        }
    }
}

pub(crate) fn validate(path: &Path, extension: &str, flag: &str) -> Result<()> {
    ensure!(
        path.extension()
            .is_some_and(|value| value.eq_ignore_ascii_case(extension)),
        "{flag} must have a .{extension} extension"
    );
    ensure!(
        !path.is_dir(),
        "output destination is a directory: {}",
        path.display()
    );

    Ok(())
}

pub(crate) fn validate_source(path: &Path) -> Result<()> {
    validate(path, "tex", "--tex-output")?;
    if path.exists() {
        let source = fs::read_to_string(path)
            .with_context(|| format!("checking {} before source export", path.display()))?;
        ensure!(
            source.starts_with("% Generated by tex-diff."),
            "--tex-output would overwrite an existing LaTeX source: {}; choose another destination",
            path.display()
        );
    }

    Ok(())
}

pub(crate) fn publish(
    source_directory: &Path,
    pdf: Option<(&Path, &Path)>,
    tex_output: Option<&Path>,
    report_output: Option<&Path>,
) -> Result<()> {
    let mut outputs = Vec::new();
    if let Some((source, destination)) = pdf {
        outputs.push((prepare(source, destination)?, destination.to_owned()));
    }
    for (source_name, destination) in [("review.tex", tex_output), ("report.json", report_output)] {
        if let Some(destination) = destination {
            outputs.push((
                prepare(&source_directory.join(source_name), destination)?,
                destination.to_owned(),
            ));
        }
    }

    if let Some(destination) = tex_output {
        export_assets(source_directory, destination)?;
    }
    for (temporary, destination) in outputs {
        temporary
            .persist(&destination)
            .with_context(|| format!("writing {}", destination.display()))?;
    }

    Ok(())
}

fn parent(path: &Path) -> &Path {
    path.parent()
        .filter(|path| !path.as_os_str().is_empty())
        .unwrap_or(Path::new("."))
}

fn prepare(source: &Path, destination: &Path) -> Result<tempfile::NamedTempFile> {
    fs::create_dir_all(parent(destination))
        .with_context(|| format!("creating output directory for {}", destination.display()))?;
    let temporary = tempfile::NamedTempFile::new_in(parent(destination))?;
    fs::copy(source, temporary.path())
        .with_context(|| format!("preparing output from {}", source.display()))?;
    temporary.as_file().sync_all()?;

    Ok(temporary)
}

#[derive(Clone, Copy)]
enum AssetAction {
    Copy,
    Verify,
}

fn process_assets(source: &Path, target: &Path, action: AssetAction) -> Result<()> {
    for entry in fs::read_dir(source)? {
        let entry = entry?;
        let output = target.join(entry.file_name());
        if entry.file_type()?.is_dir() {
            if matches!(action, AssetAction::Copy) {
                fs::create_dir(&output)?;
            }
            process_assets(&entry.path(), &output, action)?;
        } else {
            match action {
                AssetAction::Copy => {
                    fs::copy(entry.path(), output)?;
                }
                AssetAction::Verify => {
                    ensure!(
                        fs::read(entry.path())? == fs::read(&output)?,
                        "existing exported asset differs: {}",
                        output.display()
                    );
                }
            }
        }
    }

    Ok(())
}

fn export_assets(source: &Path, destination: &Path) -> Result<()> {
    for entry in fs::read_dir(source)? {
        let entry = entry?;
        if !entry.file_type()?.is_dir()
            || !entry
                .file_name()
                .to_string_lossy()
                .starts_with("tex-diff-assets-")
        {
            continue;
        }

        let output = parent(destination).join(entry.file_name());
        if output.exists() {
            ensure!(
                output.is_dir(),
                "asset destination is not a directory: {}",
                output.display()
            );
            process_assets(&entry.path(), &output, AssetAction::Verify)?;
        } else {
            let temporary = tempfile::tempdir_in(parent(destination))?;
            process_assets(&entry.path(), temporary.path(), AssetAction::Copy)?;
            fs::rename(temporary.path(), &output)
                .with_context(|| format!("saving assets to {}", output.display()))?;
        }
    }

    Ok(())
}
